### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Sovendus-GmbH/sovendus_select_product_tracking_template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation [URL](https://github.com/Sovendus-GmbH/sovendus_pressproduct_gtm_template) mentioned in the manifest file is not valid. It shows "404 page not found" error. Please provide a valid url.
![Screenshot 2021-05-28 10 03 21 AM](https://user-images.githubusercontent.com/53495700/120018649-52ce7e80-bf9c-11eb-922f-700fd1f04050.png)

**Comment by sovfox** [comment]
URL has been adjusted to point to valid location. Thanks for the feedback.
